const allGames = [
  "Cluster Rush",
  "Plants vs Brainrots",
  "Rooftop Snipers",
  "OvO",
  "Gun Mayhem 2",
  "Polytrack",
  "Temple Run",
  "Minecraft 1.11.2",
  "Minecraft Flame",
  "Brawl Heroes",
  "Block Blast",
  "Run 3",
  "My Friend Pedro",
  "Space Waves",
  "Hole.io",
  "Bitlife",
  "The Impossible Quiz",
  "Monkey Mart",
  "Minecraft 1.8.8",
  "St­eal a Brainrot",
  "Minecraft Astra",
  "Trash Clash Royale",
  "Paper.io 2",
  "Roblox Blade Ball",
  "Gun Mayhem",
  "Roblox Color Run",
  "Drive Mad",
  "Doodle Jump",
  "Portal",
  "Minecraft Resent",
  "Plants vs Zombies",
  "Angry Birds",
  "Bob The Robber",
  "TABS",
  "Smash Karts",
  "Happy Wheels",
  "Subway Surfers",
  "Fury Wars",
  "Minecraft 1.20.1",
  "Learn To Fly",
  "Ultrakill",
  "Minecraft Tuff 1.12.2",
  "1v1.lol",
  "Fall.io",
  "S­mashy Road",
  "Minecraft Parkour",
  "Bloons Tower Defense",
  "Roblox Rob The Bank",
  "Taxi Drift",
  "Vex 5",
  "Geometry Dash",
  "Run 3",
  "Spacebar Clicker",
  "Tunnel Rush",
  "Infinite Craft",
  "Time Shooter 3 SWAT",
  "Crazy Cattle 3D",
  "Raft",
  "Duck Life 5",
  "Deltarune",
  "Flash Games",
  "Stickman Hook",
  "Retro Bowl",
  "Roblox Obby",
  "Skibidi Toilet.io",
  "Mask­ed Special Forces",
  "Duck Life 3",
  "Gangsta Island",
  "Car Simulator",
  "Blockpost",
  "JustFall.lol",
  "S­lope",
  "Pixel Shooter",
  "Smashy Road",
  "Tomb of the Mask",
  "Plants vs Zombies",
  "Moto X3M",
  "Drift Boss",
  "Henry Stickmin",
  "Hollow Knight",
  "Angry Birds",
  "Minecraft 1.9.4",
  "FNAF",
  "Tiny Fishing",
  "Grow a Garden",
  "Stick War",
  "Spacebar Clicker",
  "Tanuki Sunset",
  "OvO",
  "Drive Mad",
  "Minecraft Astra",
  "Minecraft 1.20.1",
  "Undertale Yellow",
  "99 Nights in the Forest",
  "Rocket League",
  "Smashy Road",
  "Basketball Stars",
  "Cookie Clicker",
  "Roblox Obby"
];

adminGames = [

];
