const allGames = [
  "Cluster Rush",
  "Plants vs Brainrots",
  "Rooftop Snipers",
  "OvO",
  "Gun Mayhem 2",
  "Polytrack",
  "Temple Run",
  "Minecraft 1.11.2",
  "Minecraft Flame",
  "Brawl Heroes",
  "Block Blast",
  "My Friend Pedro",
  "Space Waves",
  "Hole.io",
  "Bitlife",
  "The Impossible Quiz",
  "Monkey Mart",
  "Minecraft 1.8.8",
  "Steal a Brainrot",
  "Trash Clash Royale",
  "Paper.io 2",
  "Roblox Blade Ball",
  "Gun Mayhem",
  "Roblox Color Run",
  "Doodle Jump",
  "Portal",
  "Minecraft Resent",
  "Plants vs Zombies",
  "Bob The Robber",
  "TABS",
  "Smash Karts",
  "Happy Wheels",
  "Subway Surfers",
  "Fury Wars",
  "Learn To Fly",
  "Ultrakill",
  "Minecraft Tuff 1.12.2",
  "1v1.lol",
  "Fall.io",
  "Minecraft Parkour",
  "Bloons Tower Defense",
  "Roblox Rob The Bank",
  "Taxi Drift",
  "Vex 5",
  "Geometry Dash",
  "Run 3",
  "Spacebar Clicker",
  "Tunnel Rush",
  "Infinite Craft",
  "Time Shooter 3 SWAT",
  "Crazy Cattle 3D",
  "Raft",
  "Duck Life 5",
  "Deltarune",
  "Flash Games",
  "Stickman Hook",
  "Retro Bowl",
  "Roblox Obby",
  "Skibidi Toilet.io",
  "Masked Special Forces",
  "Duck Life 3",
  "Gangsta Island",
  "Car Simulator",
  "Blockpost",
  "JustFall.lol",
  "Slope",
  "Pixel Shooter",
  "Tomb of the Mask",
  "Moto X3M",
  "Drift Boss",
  "Henry Stickmin",
  "Hollow Knight",
  "Angry Birds",
  "Minecraft 1.9.4",
  "FNAF",
  "Tiny Fishing",
  "Grow a Garden",
  "Stick War",
  "Tanuki Sunset",
  "Drive Mad",
  "Minecraft Astra",
  "Minecraft 1.20.1",
  "Undertale Yellow",
  "99 Nights in the Forest",
  "Rocket League",
  "Smashy Road",
  "Basketball Stars",
  "Cookie Clicker",
  "Duck Life 4",
  "Station Saturn",
  "Game Requests",
];

adminGames = [
  "Add Message",
  "Push Games",
];
